### ISSUE TITLE
Description? Anything about how to add this to server?

### ISSUE THREAD

**Issue by oc-tk** [Anceph/gamba-bot#2]
Hi, I am interested in this project and I would like to add it to my Discord Server. Does code needs to be updated? I have seen references to the MongoDB. What are requirements?

**Comment by exababy** [comment]
just code bro don't use if you don't understand

**Comment by Anceph** [comment]
Sorry for the late response, I didn't see the mail. As for the description I do all of my bots for fun and leave the repo public so If anyone wants to take a look, they can. That's why there isn't any "How to Use" kind of text that explains the project. My projects  are janky and making it a public bot would probably be a bad idea unless someone revisions the whole project.

In the current state bot would work just fine. Maybe some bugs here and there but overall It's not bad. You can create a new project from MongoDB and get a free database. Then fill the ".env.example" and rename it to ".env". Only thing after this is If you want to use commands that feature emojis (Blackjack, Rank System), you have to get those emojis in a server that your bot is in and change Guild ID to that server in the src/config.json.
